### ISSUE TITLE
AssertionError: decrunch .dist-info directory not found

### ISSUE THREAD

**Issue by Nicofisi** [HearthSim/decrunch#8]
Hi!
```
$ pip3 install decrunch || pip3 --version && python --version
Collecting decrunch
Installing collected packages: decrunch
Exception:
Traceback (most recent call last):
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages\pip\wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: decrunch .dist-info directory not found
pip 9.0.1 from c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages (python 3.6)
Python 3.6.3
```
Windows 10 pro btw

What can I do? :heart: Need it for your other tools

**Comment by jleclanche** [comment]
This is on WSL?

Completely untested on Windows so, uh, I think you'll have to debug this one yourself most likely. Maybe @Mischanix can help.

**Comment by Nicofisi** [comment]
I fixed it after an hour, IIRC I deleted the whole `c:\users\nicofisi\appdata\local\programs\python\python36\lib\site-packages`, installed pip again, and then either I downloaded and installed it from here or a simple `pip3 install unitypack` worked.

I don't really use Python for anything else so it's not a problem for me that I lost previously downloaded packages ;)

Thanks for the great tools and Marry Christmas anyways!

**Comment by jleclanche** [comment]
Cool!
